#+title: Create a custom component in ESPIDF
#+date: [2024-01-28 Sun]
#+OPTIONS: ^:nil
* How do you create a custom component in ESPIDF?
The build system documentation is huge and understanding how to create a custom component to modularize your project is daunting task.
So I will explain a beginner friendly way to create custom component.

#+begin_src
- myProject/
             - CMakeLists.txt
             - sdkconfig
             - components/ - component1/ - CMakeLists.txt
                                         - Kconfig
                                         - src1.c
                           - component2/ - CMakeLists.txt
                                         - Kconfig
                                         - src1.c
                                         - include/ - component2.h
             - main/       - CMakeLists.txt
                           - main.c
             - build/
#+end_src
This is structure of the example project

myProject/CMakeList.txt
#+begin_src
# For more information about build system see
# https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html
# The following five lines of boilerplate have to be in your project's
# CMakeLists in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(main)
#+end_src
This is contents of example project from ESPIDF github page.This is minimum requirement to build your project with idf.py.
There is details description of these lines in [[https://docs.espressif.com/projects/esp-idf/en/v5.1.2/esp32/api-guides/build-system.html#minimal-example-cmakelists][minimum example CMakeLists]].

components/component1/CMakeLists.txt
#+begin_src
idf_component_register(SRCS "src1.c"
                        INCLUDE_DIRS ".")
#+end_src
This is the contents of component1 CMakeLists. These SRCS variable is used to add all the .c files in the directory/component and the INCLUDE_DIRS variable is used to add the include folder which will import the .h files.

components/component2/CMakeLists.txt
#+begin_src
idf_component_register(SRCS "src2.c"
                        INCLUDE_DIRS "include")


#+end_src
This is the contents of component2 CMakeLists. I just wanted to show that you can include .h files in this format as well.

Using idf_component_register to register the component will give the cmake build system to compile and link your component to firmware.

** If you want to use custom folder
By default ESPIDF will look for components in myProject/components folder. If you want to declare your components in another folder for example: myProject/modules.
you can set it using this variable EXTRA_COMPONENT_DIRS.

#+begin_src
(set EXTRA_COMPONENT_DIRS "./modules")
#+end_src
