#+TITLE: Interfacing SSD1306 128*64 Led Display With ESP32 in EspIDF
#+AUTHOR: Vijay Vinayaraj
#+OPTIONS: toc:nil
* Introduction

They guys just want to show you how to interface with a SSD1306 led display with esp32 in ESPIDF. The official documenation might overwhelm the average programmer.
I have used the oled display with the [[https://github.com/adafruit/Adafruit_SSD1306][Adafruit SSD1306]] library. I want to try out ESPIDF and had a oled display lying around. Lets get to it without boring you.
I have used the minimum possible code you interface with ssd1306 if you want to go extreme I have given a great repo for you go through.


I will link the datasheet of [[https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf][SSD1306]] here.
There is github repo that has detailed code for interfacing with oled. I will link it [[https://github.com/nopnop2002/esp-idf-ssd1306/blob/master/TextDemo/main/main.c][here]]. 
I am using ESPIDF v5. I have setup the project with platformio and vscode.
I won't be explaining how to I2C work there are great articles on that which can you be found by a google search.

* Intialization
#+CAPTION: block-diagram of SSD1306 Initialization
#+NAME: block-diagram
#+ATTR_HTML: :width 400px
file:./ssd1306-block-diagram.png

This is the block diagram shown on the last page of the datasheet. We have to intialize ssd1306 according to the block diagram.
For making it easy for you I have declared all the registers of ssd1306.
#+begin_src c
#define OLED_I2C_ADDRESS   0x3C

// Control byte
#define OLED_CONTROL_BYTE_CMD_SINGLE    0x80
#define OLED_CONTROL_BYTE_CMD_STREAM    0x00
#define OLED_CONTROL_BYTE_DATA_STREAM   0x40

// Fundamental commands (pg.28)
#define OLED_CMD_SET_CONTRAST           0x81   
#define OLED_CMD_DISPLAY_RAM            0xA4
#define OLED_CMD_DISPLAY_ALLON          0xA5
#define OLED_CMD_DISPLAY_NORMAL         0xA6
#define OLED_CMD_DISPLAY_INVERTED       0xA7
#define OLED_CMD_DISPLAY_OFF            0xAE
#define OLED_CMD_DISPLAY_ON             0xAF

// Addressing Command Table (pg.30)
#define OLED_CMD_SET_MEMORY_ADDR_MODE   0x20   
#define OLED_CMD_SET_COLUMN_RANGE       0x21    
#define OLED_CMD_SET_PAGE_RANGE         0x22    

// Hardware Config (pg.31)
#define OLED_CMD_SET_DISPLAY_START_LINE 0x40
#define OLED_CMD_SET_SEGMENT_REMAP      0xA1    
#define OLED_CMD_SET_MUX_RATIO          0xA8   
#define OLED_CMD_SET_COM_SCAN_MODE      0xC8    
#define OLED_CMD_SET_DISPLAY_OFFSET     0xD3    
#define OLED_CMD_SET_COM_PIN_MAP        0xDA   
#define OLED_CMD_NOP                    0xE3    

// Timing and Driving Scheme (pg.32)
#define OLED_CMD_SET_DISPLAY_CLK_DIV    0xD5    
#define OLED_CMD_SET_PRECHARGE          0xD9    
#define OLED_CMD_SET_VCOMH_DESELCT      0xDB    

// Charge Pump (pg.62)
#define OLED_CMD_SET_CHARGE_PUMP        0x8D    

#+end_src

You can copy this registers to use in your project. These registers are taken from the datasheet.

** Initializing I2C
#+begin_src c
void i2c_master_init()
{
	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(I2C_NUM_0, &i2c_config);
	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

#+end_src



** Initializing SSD1306
Init function is used to intialize all the registers according to the datasheet block diagram.
#+begin_src c
void ssd1306_init() {
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	
	i2c_master_write_byte(cmd,OLED_CONTROL_BYTE_CMD_STREAM,true);
	i2c_master_write_byte(cmd,OLED_CMD_DISPLAY_OFF,true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_MUX_RATIO,true);
	i2c_master_write_byte(cmd,0x3F,true);

	i2c_master_write_byte(cmd,OLED_CMD_SET_DISPLAY_OFFSET,true);
	i2c_master_write_byte(cmd,0x00,true);
    
	i2c_master_write_byte(cmd,OLED_CMD_SET_DISPLAY_START_LINE,true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_SEGMENT_REMAP,true);
    
	i2c_master_write_byte(cmd,OLED_CMD_SET_COM_SCAN_MODE,true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_COM_PIN_MAP,true);
	i2c_master_write_byte(cmd,0x12,true);

	i2c_master_write_byte(cmd,OLED_CMD_SET_CONTRAST,true);
	i2c_master_write_byte(cmd,0x7F,true);

	i2c_master_write_byte(cmd,OLED_CMD_DISPLAY_RAM,true);

	i2c_master_write_byte(cmd,OLED_CMD_DISPLAY_NORMAL,true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_DISPLAY_CLK_DIV,true);
	i2c_master_write_byte(cmd,0x80,true);
	
	i2c_master_write_byte(cmd,OLED_CMD_SET_CHARGE_PUMP,true);
	i2c_master_write_byte(cmd,0x14,true);

	i2c_master_write_byte(cmd,OLED_CMD_SET_PRECHARGE,true);
	i2c_master_write_byte(cmd,0x22,true);

	i2c_master_write_byte(cmd,OLED_CMD_SET_VCOMH_DESELCT,true);
	i2c_master_write_byte(cmd,0x30,true);

	i2c_master_write_byte(cmd,OLED_CMD_SET_MEMORY_ADDR_MODE,true);
	i2c_master_write_byte(cmd,0x00,true);

	i2c_master_write_byte(cmd,OLED_CMD_DISPLAY_ON,true);
    i2c_master_stop(cmd);

	espRc =i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "OLED configured successfully");
	} else {
		ESP_LOGE(tag, "OLED configuration failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
}
#+end_src


** Displaying Text

I have used the [[https://github.com/nopnop2002/esp-idf-ssd1306/blob/master/components/ssd1306/font8x8_basic.h][fonts]] from the github repo mentioned above.

#+begin_src c
void display(char *text){
	esp_err_t espRc;
	uint8_t text_len = strlen(text);
	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd,OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_COLUMN_RANGE, true);
	i2c_master_write_byte(cmd,0x00, true);
	i2c_master_write_byte(cmd,0x7F, true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_PAGE_RANGE, true);
	i2c_master_write_byte(cmd,0, true);
	i2c_master_write_byte(cmd,0x07, true);


	i2c_master_stop(cmd);
	espRc =i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "OLED cc successfully");
	} else {
		ESP_LOGE(tag, "OLED cc failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
	for(uint16_t i=0;i<text_len;i++){
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd,OLED_CONTROL_BYTE_DATA_STREAM, true);
	
	i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)text[i]], 8, true);
	   
	i2c_master_stop(cmd);  
	espRc =i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		if (espRc == ESP_OK) {
			ESP_LOGI(tag, "OLED dd successfully");
			ESP_LOGI(tag, "%c",text[i]);
		} else {
			ESP_LOGE(tag, "OLED ddfailed. code: 0x%.2X", espRc);
		}
    i2c_cmd_link_delete(cmd);
	}
	
}
#+end_src


** Clear Screen
#+begin_src c
void clearScreen(){
esp_err_t espRc;
	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd,OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_COLUMN_RANGE, true);
	i2c_master_write_byte(cmd,0x00, true);
	i2c_master_write_byte(cmd,0x7F, true);
	i2c_master_write_byte(cmd,OLED_CMD_SET_PAGE_RANGE, true);
	i2c_master_write_byte(cmd,0, true);
	i2c_master_write_byte(cmd,0x07, true);


	i2c_master_stop(cmd);
	espRc =i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "OLED cc successfully");
	} else {
		ESP_LOGE(tag, "OLED cc failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
	for(uint16_t i=0;i<128;i++){
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd,OLED_CONTROL_BYTE_DATA_STREAM, true);
	
	i2c_master_write(cmd, font8x8_basic_tr[0], 8, true);
	   
	i2c_master_stop(cmd);  
	espRc =i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		if (espRc == ESP_OK) {
			ESP_LOGI(tag, "OLED cleared successfully");
		} else {
			ESP_LOGE(tag, "OLED ddfailed. code: 0x%.2X", espRc);
		}
        i2c_cmd_link_delete(cmd);
	}
}
#+end_src

* Conclusion

There is only minimum code for getting up and running with oled display. For displaying Images you can refer the github repo.
